version: "3"
services:
  node:
    container_name: node
    hostname: node
    image: node
    stdin_open: true
    tty: true
    working_dir: /code
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    depends_on:
      - btcsuite

  btcsuite:
    container_name: btcsuite
    hostname: btcsuite
    image: btcsuite
    build: ./btcsuite
    restart: unless-stopped
    ports:
      - 18555:18555
      - 18556:18556

volumes:
  node_modules:
  # btcd_data:
  # btcd_logs:
